name: Swipe
description: Swipe project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^5.0.4
  argon2: ^1.0.1
  bloc: ^8.1.1
  buttons_tabbar: ^1.3.6
  card_swiper: ^2.0.4
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_database: ^10.0.15
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.2.2
  lottie: ^2.2.0
  nanoid: ^1.0.0
  permission_handler: ^10.2.0
  provider: ^6.0.5
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.18
  validators: ^3.0.0
  firebase_storage: ^11.1.1
  firebase_messaging: ^14.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  connectivity_plus: ^3.0.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0

dependency_overrides:
  intl: ^0.17.0

flutter:
  assets:
    - assets/dev.env
    - assets/prod.env
    - assets/images/
    - assets/lotties/
  generate: true
  uses-material-design: true

  fonts:
    - family: Arista
      fonts:
        - asset: assets/font/Arista-Pro-Alternate-Bold-trial.ttf
        - asset: assets/font/Arista-Pro-Alternate-Fat-trial.ttf
        - asset: assets/font/Arista-Pro-Alternate-Light-trial.ttf
        - asset: assets/font/Arista-Pro-Bold-trial.ttf
        - asset: assets/font/Arista-Pro-Fat-trial.ttf
        - asset: assets/font/Arista-Pro-Light-trial.ttf
    - family: AllRoundGothic
      fonts:
        - asset: assets/font/AllRoundGothic-Bold.ttf
        - asset: assets/font/AllRoundGothic-BoldOblique.ttf
        - asset: assets/font/AllRoundGothic-Book.ttf
        - asset: assets/font/AllRoundGothic-BookOblique.ttf
        - asset: assets/font/AllRoundGothic-Demi.ttf
        - asset: assets/font/AllRoundGothic-DemiOblique.ttf
        - asset: assets/font/AllRoundGothic-Medium.ttf
        - asset: assets/font/AllRoundGothic-Medium.ttf
        - asset: assets/font/AllRoundGothic-XLig.ttf
        - asset: assets/font/AllRoundGothic-XLig.ttf
    - family: Handlee
      fonts:
        - asset: assets/font/Handlee-Regular.ttf
        # fonts:
        #   - family: Schyler
        #     fonts:
        #       - asset: fonts/Schyler-Regular.ttf
        #       - asset: fonts/Schyler-Italic.ttf
        #         style: italic
        #   - family: Trajan Pro
        #     fonts:
        #       - asset: fonts/TrajanPro.ttf
        #       - asset: fonts/TrajanPro_Bold.ttf
        #         weight: 700
        #
        # For details regarding fonts from package dependencies,
        # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true