name: Swipe
description: Swipe project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^5.0.4
  argon2: ^1.0.1
  bloc: ^8.1.0
  buttons_tabbar: ^1.3.6
  card_swiper: ^2.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  lottie: ^2.1.0
  nanoid: ^1.0.0
  permission_handler: ^10.2.0
  salomon_bottom_bar: ^3.3.1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  connectivity_plus: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  assets:
    - assets/dev.env
    - assets/prod.env
    - assets/images/
    - assets/lotties/
  generate: true
  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true